name: CI

on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "17"

      - name: Install nodejs dependencies
        run: npm ci

      - name: Build TS
        run: npm run build
